// <auto-generated />
using System;
using GoodHamburger.Infrastructure.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoodHamburger.Infrastructure.Migrations
{
    [DbContext(typeof(GoodHamburgerDbContext))]
    partial class GoodHamburgerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("GoodHamburger.Domain.Entidades.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PercentualDesconto")
                        .HasColumnType("decimal(5,4)");

                    b.HasKey("Id");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("GoodHamburger.Domain.Entidades.Pedido", b =>
                {
                    b.OwnsMany("GoodHamburger.Domain.Entidades.ItemCardapio", "_itens", b1 =>
                        {
                            b1.Property<Guid>("PedidoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Codigo")
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Preco")
                                .HasColumnType("decimal(10,2)");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("PedidoId", "Codigo");

                            b1.ToTable("ItensPedido", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PedidoId");
                        });

                    b.Navigation("_itens");
                });
#pragma warning restore 612, 618
        }
    }
}
